# Website settings
url: "https://www.piether.be"

# Internal nav
nav:
  main:
    blog: "/"
    about: "/about"
  writing:
    all: "/"
    popular: "/popular"
    tags: "/tags"
    rss: "/feed.xml"

# Bio settings
name: "Pieter Herroelen"
description: "The home page of Pieter Herroelen"
thumbnail_path: "profile-photos/pieter-herroelen-small.jpg"
website_repo_url: "https://github.com/piether/piether-homepage"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/piether"
    label: "Twitter"
    icon: "twitter-square"
    username: "@piether"
  linkedin:
    url: "https://www.linkedin.com/in/pieterherroelen"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/piether/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:pieter@dovetail.be"
    label: "Email"
    value: "pieter@dovetail.be"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: "Europe/Brussels"
repository: piether/piether-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
